"""
ExportService: Handles multi-format syllabus exports for Task 2 (Course Planner).
Supports native JSON, formatted Markdown, and in-memory PyMuPDF (fitz) PDF generation, with DOCX architectural stubs.
"""
import io
import json
from typing import Dict, Any, Optional
import fitz  # PyMuPDF
from app.planner.models import CoursePlan
from app.core.logger import get_logger

logger = get_logger(__name__)

class ExportService:
    """
    Orchestrates transformations of Pydantic CoursePlan schemas into shareable document artifacts.
    """

    @staticmethod
    def export_to_markdown(plan: CoursePlan) -> str:
        """
        Converts a CoursePlan into an structured GitHub-flavored Markdown syllabus.
        """
        lines = []
        lines.append(f"# {plan.title or 'Untitled Course Syllabus'}")
        lines.append(f"**Subject:** {plan.subject or 'General'} | **Target Audience:** {plan.target_audience or 'Open'}\n")
        
        if plan.description:
            lines.append("## Course Overview")
            lines.append(f"{plan.description}\n")
            
        if plan.learning_outcomes:
            lines.append("## Key Learning Outcomes")
            for outcome in plan.learning_outcomes:
                lines.append(f"- {outcome}")
            lines.append("")
            
        if plan.prerequisites:
            lines.append("## Prerequisites")
            for prereq in plan.prerequisites:
                lines.append(f"- {prereq}")
            lines.append("")
            
        lines.append("## Curriculum Modules\n")
        
        for idx, mod in enumerate(plan.modules, 1):
            lines.append(f"### Module {idx}: {mod.title}")
            lines.append(f"**Difficulty:** {mod.difficulty} | **Estimated Duration:** {mod.estimated_duration_hours} Hours")
            if mod.description:
                lines.append(f"_{mod.description}_\n")
                
            if mod.objectives:
                lines.append("**Module Objectives:**")
                for obj in mod.objectives:
                    lines.append(f"  * {obj}")
                lines.append("")
                
            if mod.lessons:
                lines.append("**Lessons:**")
                for l in mod.lessons:
                    lines.append(f"  1. **{l.title}** ({l.estimated_duration_minutes} min) — {l.description}")
                lines.append("")
                
            if mod.resources:
                lines.append("**Recommended Public Resources:**")
                for res in mod.resources:
                    link = f" ([Link]({res.url}))" if res.url else ""
                    lines.append(f"  * [{res.type.upper()}] **{res.title}**{link}")
                lines.append("")
                
            if mod.projects:
                lines.append("**Hands-on Projects:**")
                for p in mod.projects:
                    lines.append(f"  * **{p.title}** ({p.difficulty}): {p.description}")
                lines.append("")
                
            if mod.assessments:
                lines.append("**Assessments:**")
                for a in mod.assessments:
                    lines.append(f"  * **{a.title}** ({a.type}): {a.description}")
                lines.append("")
                
            lines.append("---\n")
            
        lines.append("_\nGenerated by SamaSocial AI Course Planning Assistant_")
        return "\n".join(lines)

    @classmethod
    def export_to_pdf_bytes(cls, plan: CoursePlan) -> bytes:
        """
        Generates a PDF document in memory using PyMuPDF (fitz) and returns the binary stream.
        """
        doc = fitz.open()
        page = doc.new_page(width=595, height=842) # A4 dimensions in points
        
        y_cursor = 50
        margin_x = 50
        page_width = 595 - 2 * margin_x
        
        def add_text(text: str, fontname: str = "helv", fontsize: float = 11, line_spacing: float = 15, color: tuple = (0.1, 0.1, 0.1)):
            nonlocal y_cursor, page
            rect = fitz.Rect(margin_x, y_cursor, margin_x + page_width, 800)
            
            # Use TextWriter or insert_textbox for clean line wrapping
            res = page.insert_textbox(rect, text, fontname=fontname, fontsize=fontsize, color=color)
            if res < 0: # Buffer overflowed current page, make new page
                page = doc.new_page(width=595, height=842)
                y_cursor = 50
                rect = fitz.Rect(margin_x, y_cursor, margin_x + page_width, 800)
                page.insert_textbox(rect, text, fontname=fontname, fontsize=fontsize, color=color)
            
            # Estimate consumed lines height
            approx_lines = max(1, len(text) // 70 + 1)
            y_cursor += approx_lines * line_spacing + 5
            if y_cursor > 780:
                page = doc.new_page(width=595, height=842)
                y_cursor = 50

        # Title
        add_text(f"Course Syllabus: {plan.title or 'Untitled Plan'}", fontname="hebo", fontsize=18, line_spacing=22, color=(0.1, 0.2, 0.6))
        add_text(f"Subject: {plan.subject} | Target Audience: {plan.target_audience}", fontname="hebo", fontsize=12, line_spacing=16, color=(0.3, 0.3, 0.3))
        y_cursor += 10
        
        if plan.description:
            add_text(f"Overview: {plan.description}", fontsize=11, line_spacing=15)
            y_cursor += 10
            
        if plan.learning_outcomes:
            add_text("Key Learning Outcomes:", fontname="hebo", fontsize=13, line_spacing=16, color=(0.1, 0.4, 0.2))
            for out in plan.learning_outcomes:
                add_text(f"  • {out}", fontsize=10, line_spacing=13)
            y_cursor += 10
            
        add_text("Curriculum Structure:", fontname="hebo", fontsize=14, line_spacing=18, color=(0.1, 0.2, 0.6))
        y_cursor += 5
        
        for idx, mod in enumerate(plan.modules, 1):
            add_text(f"Module {idx}: {mod.title} ({mod.difficulty}, ~{mod.estimated_duration_hours} hrs)", fontname="hebo", fontsize=12, line_spacing=16, color=(0.2, 0.2, 0.2))
            if mod.description:
                add_text(f"  {mod.description}", fontsize=10, line_spacing=14, color=(0.4, 0.4, 0.4))
            for l in mod.lessons:
                add_text(f"    - Lesson: {l.title} ({l.estimated_duration_minutes} min)", fontsize=10, line_spacing=13)
            for r in mod.resources:
                url_text = f" ({r.url})" if r.url else ""
                add_text(f"    - Resource: [{r.type.upper()}] {r.title}{url_text}", fontsize=9, line_spacing=12, color=(0.0, 0.4, 0.8))
            for p in mod.projects:
                add_text(f"    - Project: {p.title} ({p.difficulty})", fontsize=10, line_spacing=13, color=(0.6, 0.3, 0.0))
            y_cursor += 10
            
        pdf_bytes = doc.tobytes()
        doc.close()
        logger.info("Successfully generated PDF syllabus document in memory.")
        return pdf_bytes

    @staticmethod
    def export_to_docx_stub(plan: CoursePlan) -> Dict[str, str]:
        """
        Extensible architectural interface preparing for native Microsoft Word (.docx) export.
        """
        return {
            "status": "not_implemented",
            "format": "docx",
            "message": "DOCX generator architectural stub ready for python-docx integration.",
            "title": plan.title
        }
